# baseURL = 'http://www.omberaldi.de/'
baseURL = 'http://www.marco-sanna.de/omberaldi/'
languageCode = 'de-de'
title = 'Omberaldi'
theme = 'ananke'
[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1
